Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [24]:

def get_moving_average(l,n):
    moving_avg=[]
    for i in range(0,len(l)-n+1):
        su=sum(l[i:i+n])
        moving_avg.append(su/n)
    return moving_avg

In [25]:
l=[1,2,3,4,5,6,7,8,9,10]
n=4
get_moving_average(l,n)


[2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5]

In [26]:
l_test=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n_test=3
get_moving_average(l_test,n_test)

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]

Write a function so that the columns of the output matrix are powers of the input
vector.

In [44]:
import numpy as np
from numpy.random import randint as ri
i_v = ri([1,2,3,4,5])

In [45]:
i_v

array([0, 1, 2, 2, 3])

In [46]:
res = []
for idx in range(1, 10, K):
    sub = [idx, idx + 1, idx + 2]
    res.append(sub)

NameError: name 'K' is not defined

In [51]:
n=(i_v).size

m=np.column_stack([(i_v)**(n-i-1) for i in range(n)])
print(m)


5
[[ 0  0  0  0  1]
 [ 1  1  1  1  1]
 [16  8  4  2  1]
 [16  8  4  2  1]
 [81 27  9  3  1]]


In [37]:
import numpy as np 
x=np.array([1,2,3,4,5]) 
N=5 
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix) 

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
